### ISSUE TITLE
community.crypto didn't work because of lib issue.

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [ownport/portable-ansible#26]
We in a team are using portable_ansible.  We found that since the builder is using alpine image, it pulled the cryptography dependency with musllinux variant.  However, our target platform are not alpine.  As a result, there was library import error since a normal distro won't have musl libc.

There is no expected fix, just a note to everyone else.

**Comment by rtsui-harmonicinc** [comment]
Kubespray is using this module in 2.27.0, and it would fail because of the use of the filter in PR https://github.com/kubernetes-sigs/kubespray/pull/11758

Input
```yaml
name: Create kubeadm client config (show only)
  ansible.builtin.debug:
    msg: |
      {% if ca_cert_content is defined %}
      caCertHashes:
sha256:{{ (ca_cert_content.content | b64decode | community.crypto.x509_certificate_info).public_key_fingerprints.sha256.replace(':', '') }}
      {% else %}
          unsafeSkipCAVerification: true
      {% endif %}
  # when: ('kube_control_plane' not in group_names)
```

Output
```log
"NameError: name 'x509' is not defined"
```
